fix file name

diff --git a/bin/dt b/bin/dt
--- a/bin/dt
+++ b/bin/dt
@@ -13,7 +13,7 @@ echo -e "DT 21.03\n"
 [ -f $DT_HOME/conf/DT.conf ] && source $DT_HOME/conf/DT.conf && echo 'Loading DT environment...OK'
 
 
-[ "$#" != 1 ] && echo 'dt [sysinfo | sysprep | build | list | restart]' && exit 1
+[ "$#" != 1 ] && echo 'dt [sysinfo | sysprep | build | changn | restart]' && exit 1
 c="sysinfo sysprep build list restart"
 [[ ! "${c}" =~ "$1" ]] && echo "Oops, wrong command" && exit 1
 
@@ -40,7 +40,6 @@ sysprep)
   do
     nc -w 2 -z $x 22 &>/dev/null
     [ "$?" != "0" ] && continue
-    ssh $x "wget -qO - $WEB_URL/config/mactohost | sudo tee /etc/mactohost &>/dev/null [ \"$?\" == \"0\" ] && echo 'mactohost copied' || echo 'failed' "
     ssh $x "wget -qO - $WEB_URL/script/sysprep | bash"
     echo ""
   done
@@ -60,7 +59,12 @@ build)
     ssh $x "wget -qO - $WEB_URL/script/build | bash  /dev/stdin $WEB_URL"
   done
   ;;
-list)
+changn)
+  for x in $i
+  do
+    ssh $x "wget -qO - $WEB_URL/config/mactohost | sudo tee /etc/mactohost &>/dev/null; [ \"$?\" == \"0\" ] && echo 'mactohost copied' || echo 'failed' "
+  done
+
   ;;
 restart)
   read -p "Are you sure ? (YES/NO) " ans
